#!/bin/bash
#

#----------------------------------------------------------------------------//
# => HELPER FUNCTIONS
#----------------------------------------------------------------------------//
function color_echo(){
	# Usage  : color_echo "string" color
	# Credit : http://stackoverflow.com/a/23006365/428786
	local exp=$1;
	local color=$2;
	if ! [[ $color =~ '^[0-9]$' ]] ; then
		case $(echo $color | tr '[:upper:]' '[:lower:]') in
			black) color=0 ;;
			red) color=1 ;;
			green) color=2 ;;
			yellow) color=3 ;;
			blue) color=4 ;;
			magenta) color=5 ;;
			cyan) color=6 ;;
			white|*) color=7 ;; # white or invalid color
		esac
	fi
	tput setaf $color;
	printf "\n$exp\n"
	tput sgr0;
}


#----------------------------------------------------------------------------//
# => SET TRAP
#----------------------------------------------------------------------------//
# Exit install script if any command fails
set -e

# Require root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi


#----------------------------------------------------------------------------//
# => ADDING NEW REPOSITORIES
#----------------------------------------------------------------------------//
yum update -y


#----------------------------------------------------------------------------//
# => ADDING NEW REPOSITORIES
#----------------------------------------------------------------------------//
color_echo "Enabling EPEL and Nux Dextop Repositories ..." cyan
  rpm -Uvh https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
  rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm


#----------------------------------------------------------------------------//
# => FONT HINTING
#----------------------------------------------------------------------------//
color_echo "Installing Freetype, Cairo with infinality  ..." cyan
  yum --enablerepo=nux-dextop install -y fontconfig-infinality
  yum --enablerepo=nux-dextop install -y cairo
  yum --enablerepo=nux-dextop install -y libXft
  yum --enablerepo=nux-dextop install -y freetype-infinality

color_echo "Installing extra fonts  ..." cyan
  yum install -y webcore-fonts webcore-fonts-vista google-droid-*


#----------------------------------------------------------------------------//
# => INSTALLING EXTRA FUNCTIONALITY
#----------------------------------------------------------------------------//
color_echo "Installing NTFS support ... " cyan
  yum install -y ntfs*

color_echo "Installing Sensors for hardware temp ... " cyan
  yum install -y lm_sensors
  sensors-detect


#----------------------------------------------------------------------------//
# => INSTALLING DESKTOP SOFTWARE....
#----------------------------------------------------------------------------//
color_echo "Installing Steam ..." cyan
  yum install -y steam

color_echo "Installing Skype ..." cyan
  yum install -y skype

color_echo "Installing MP3 support with gstreamer ..." cyan
  yum install -y gstreamer gstreamer1 gstreamer-ffmpeg gstreamer-plugins-good gstreamer-plugins-ugly

color_echo "Installing VLC ..." cyan
  yum install -y vlc

color_echo "Installing LibreOffice ..." cyan
  yum install -y libreoffice

color_echo "Installing Gimp  ..." cyan
  yum install -y gimp

color_echo "Installing Transmission  ..." cyan
  yum install -y transmission
