#!/bin/bash
#############################################################################//
#
# => HELPER FUNCTIONS
#
#############################################################################//

function color_echo(){
# Usage  : color_echo "string" color
# Credit : http://stackoverflow.com/a/23006365/428786
    local exp=$1;
    local color=$2;
    if ! [[ $color =~ '^[0-9]$' ]] ; then
	case $(echo $color | tr '[:upper:]' '[:lower:]') in
	    black) color=0 ;;
	    red) color=1 ;;
	    green) color=2 ;;
	    yellow) color=3 ;;
	    blue) color=4 ;;
	    magenta) color=5 ;;
	    cyan) color=6 ;;
	    white|*) color=7 ;; # white or invalid color
	esac
    fi

    tput setaf $color;
    printf "\n$exp\n"
    tput sgr0;
}

function figlet_echo(){
    local exp=$1;
    local color=$2;
    if ! [[ $color =~ '^[0-9]$' ]] ; then
	case $(echo $color | tr '[:upper:]' '[:lower:]') in
	    black) color=0 ;;
	    red) color=1 ;;
	    green) color=2 ;;
	    yellow) color=3 ;;
	    blue) color=4 ;;
	    magenta) color=5 ;;
	    cyan) color=6 ;;
	    white|*) color=7 ;; # white or invalid color
	esac
    fi

    tput setaf $color;
    printf "\n$exp"
    tput sgr0;
}



#===============================================//
# => RBENV (RUBY) & PYENV (PYTHON)
#===============================================//

#-----------------------------//
# => rbenv
#-----------------------------//
color_echo "Installing rbenv, Ruby Version Manager ... " cyan
  #NOTE: On Ubuntu Desktop, replace all ocurrences .bash_profile
  # in this code block with .bashrc

  cd $HOME
  git clone git://github.com/sstephenson/rbenv.git .rbenv

  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.bashrc
  echo 'eval "$(rbenv init -)"' >> $HOME/.bashrc

  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.zshrc
  echo 'eval "$(rbenv init -)"' >> $HOME/.zshrc

  git clone git://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
  echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> $HOME/.bashrc
  echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> $HOME/.zshrc

  if [ -n "${BASH_VERSION}" ]; then
  	source $HOME/.bashrc
  elif [ -n "${ZSH_VERSION}" ]; then
  	source $HOME/.zshrc
  fi

  cd -

color_echo "Installing Ruby, the latest version... " cyan
  rbenv install -v 2.3.0
  rbenv global 2.3.0

color_echo "Installing Ruby on Rails ... " cyan
  gem install bundler rails
  rbenv rehash

#-----------------------------//
# => pyenv
#-----------------------------//
color_echo "Installing pyenv, Python Version Manager ... " cyan
  git clone https://github.com/yyuu/pyenv.git $HOME/.pyenv

  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc
  echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bashrc
  echo 'eval "$(pyenv init -)"' >> $HOME/.bashrc

  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.zshrc
  echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.zshrc
  echo 'eval "$(pyenv init -)"' >> $HOME/.zshrc

  if [ -n "${BASH_VERSION}" ]; then
  	source $HOME/.bashrc
  elif [ -n "${ZSH_VERSION}" ]; then
  	source $HOME/.zshrc
  fi


color_echo "Installing Python, the latest version... " cyan
  pyenv install 3.4.4
  pyenv global 3.4.4
  pyenv rehash
