#!/bin/bash
###############################################################################
#         Name: linux_ubuntu
#        Usage: ./linux_ubuntu
#
#  Description: This is a helper script that automates the installation of
#                software for Development, SysAdmin, etc.
#
# Last Updated: Mon 27 Oct 2014 12:33:43 AM CDT
#
#    Tested on: Ubuntu 14.04 LTS Trusty Tahr
#
#   Maintainer: Jose Elera (https://github.com/jelera)
#     Based on: https://github.com/thoughtbot/laptop
#      License: MIT
#               Copyright (c) 2014 Jose Elera Campana
#               Permission is hereby granted, free of charge, to any person
#               obtaining a copy of this software and associated documentation
#               files (the "Software"), to deal in the Software without
#               restriction, including without limitation the rights to use,
#               copy, modify, merge, publish, distribute, sublicense, and/or
#               sell copies of the Software, and to permit persons to whom the
#               Software is furnished to do so, subject to the following
#               conditions:
#
#               The above copyright notice and this permission notice shall be
#               included in all copies or substantial portions of the Software.
#
#               THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#               EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#               OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#               NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#               HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#               WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#               FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#               OTHER DEALINGS IN THE SOFTWARE.
###############################################################################


#----------------------------------------------------------------------------//
# => HELPER FUNCTIONS
#----------------------------------------------------------------------------//
function color_echo(){
	# Usage  : color_echo "string" color
	# Credit : http://stackoverflow.com/a/23006365/428786
	local exp=$1;
	local color=$2;
	if ! [[ $color =~ '^[0-9]$' ]] ; then
		case $(echo $color | tr '[:upper:]' '[:lower:]') in
			black) color=0 ;;
			red) color=1 ;;
			green) color=2 ;;
			yellow) color=3 ;;
			blue) color=4 ;;
			magenta) color=5 ;;
			cyan) color=6 ;;
			white|*) color=7 ;; # white or invalid color
		esac
	fi
	tput setaf $color;
	printf "\n$exp\n"
	tput sgr0;
}

silver_searcher_from_source() {
	git clone git://github.com/ggreer/the_silver_searcher.git /tmp/the_silver_searcher
	sudo yum -y install pcre-devel xz-devel pkgconfig automake gcc zlib-devel
	sh /tmp/the_silver_searcher/build.sh
	cd /tmp/the_silver_searcher
	sh build.sh
	sudo make install
	cd
	rm -rf /tmp/the_silver_searcher
}

# vim74_from_source() {
# 	cd /tmp
# 	wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
# 	tar -xjf vim-7.4.tar.bz2
# 	cd vim74
# 	./configure --with-features=huge \
# 	--enable-rubyinterp \
# 	--enable-pythoninterp \
# 	--with-python-config-dir=/usr/lib/python2.7-config \
# 	--enable-python3interp \
# 	--enable-perlinterp \
# 	--enable-cscope --prefix=/usr \
# 	--enable-luainterp \
# 	--enable-gui=gtk
# 	make && sudo make install
# 	cd
# 	rm -rf /tmp/vim74
# }

append_to_zshrc() {
	local text="$1" zshrc
	local skip_new_line="$2"

	if [[ -w "$HOME/.zshrc.local" ]]; then
		zshrc="$HOME/.zshrc.local"
	else
		zshrc="$HOME/.zshrc"
	fi

	if ! grep -Fqs "$text" "$zshrc"; then
		if (( skip_new_line )); then
			printf "%s\n" "$text" >> "$zshrc"
		else
			printf "\n%s\n" "$text" >> "$zshrc"
		fi
	fi
}


#----------------------------------------------------------------------------//
# => SET TRAP
#----------------------------------------------------------------------------//
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e


#----------------------------------------------------------------------------//
# => CHECK $HOME/.bin and .zshrc
#----------------------------------------------------------------------------//
if [[ ! -d "$HOME/.bin/" ]]; then
	mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
	touch "$HOME/.zshrc"
fi

append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'


#----------------------------------------------------------------------------//
# => CHECK LINUX DISTRO
#----------------------------------------------------------------------------//
if ! grep -qiE 'wheezy|jessie|precise|trusty' /etc/os-release; then
	color_echo "Sorry! we don't currently support that distro." red
	exit 1
fi


#----------------------------------------------------------------------------//
# => UPDATE THE SYSTEM
#----------------------------------------------------------------------------//
color_echo "Updating system packages ..." cyan
  sudo apt-get update && sudo apt-get upgrade


#----------------------------------------------------------------------------//
# => INSTALL SOFTWARE FROM REPOS
#----------------------------------------------------------------------------//
color_echo "Installing Build Essentials ..." cyan
  sudo apt-get install -y build-essential

color_echo "Installing base Ruby 2.x build dependencies ..." cyan
  sudo apt-get build-dep -y ruby

color_echo "Installing base Python 2.x build dependencies ..." cyan
  sudo apt-get build-dep -y python

color_echo "Installing base Python 3.x build dependencies ..." cyan
  sudo apt-get build-dep -y python3

color_echo "Installing Ruby, Python, Python3, Perl and Lua" cyan
  sudo apt-get install -y ruby ruby-dev ruby2.0 ruby2.0-dev python python-pip python-dev python3 python3-pip python3-dev lua lua-dev perl perl-dev

color_echo "Installing git, for source control management ..." cyan
  sudo apt-get install -y git-all

color_echo "Installing libraries for common dependencies ..." cyan
  sudo apt-get install -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libqtwebkit-dev libreadline-dev
  # TODO: sudo yum install -y gcc ncurses-devel gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison libxslt libxslt-devel libksba libksba-devel qtwebkit-devel readline-devel qt3-devel PyQt4 PyQt4-devel PyQt4-webkit PyQt4-webkit-devel

color_echo "Installing sqlite3, embeddable SQL database engine" cyan
 sudo apt-get install -y sqlite3-dev sqlite3

color_echo "Installing Postgres, a great open source relational database ..." cyan
  sudo apt-get install -y postgresql postgresql-server-dev-all

color_echo "Installing Redis, an advanced key-value database ..." cyan
  sudo apt-get install -y redis-server

color_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..." cyan
  sudo apt-get install -y exuberant-ctags

color_echo "installing Vim ..." cyan
  sudo apt-get install -y vim-gtk

color_echo "installing tmux, a terminal multiplexer" cyan
  sudo apt-get install -y tmux

color_echo "Installing ImageMagick, to crop and resize images ..." cyan
  sudo apt-get install -y imagemagick

color_echo "Installing curl ..." cyan
  sudo apt-get install -y curl

color_echo "Installing zsh ..." cyan
  sudo apt-get install -y zsh

color_echo "Installing node.js and npm ..." cyan
  sudo apt-get install -y nodejs npm

color_echo "Installing LAMP Server ..." cyan
  sudo apt-get install -y lamp-server^

color_echo "Installing jsctags, ctags for JavaScript  with Tern.js" cyan
  sudo npm install -g git://github.com/ramitos/jsctags.git

color_echo "Installing jshint, an opinionated lint program for JS" cyan
  sudo npm install -g jshint

color_echo "Installing Jedi, for enhanced Python autocompletion in Vim" cyan
  sudo pip install jedi


#----------------------------------------------------------------------------//
# => INSTALL AG, THE SILVER SEARCHER
#----------------------------------------------------------------------------//
if ! command -v ag > /dev/null; then
	color_echo "Installing The Silver Searcher, grep for programmers ..." cyan

	if yum info the_silver_searcher &> /dev/null; then
		sudo yum -y install the_silver_searcher
	else
		silver_searcher_from_source
	fi
fi


#----------------------------------------------------------------------------//
# => CHANGING THE SHELL TO ZSH
#----------------------------------------------------------------------------//
color_echo "Changing your shell to zsh ..." blue
  chsh -s $(which zsh)


#----------------------------------------------------------------------------//
# => INSTALL RBENV, RUBY AND GEMS MANAGEMENT
#----------------------------------------------------------------------------//
if [[ ! -d "$HOME/.rbenv" ]]; then
  color_echo "Installing rbenv, to change Ruby versions ..." cyan
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

    append_to_zshrc 'export PATH="$HOME/.rbenv/bin:$PATH"'
    append_to_zshrc 'eval "$(rbenv init - zsh --no-rehash)"' 1

    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init - zsh)"
fi

if [[ ! -d "$HOME/.rbenv/plugins/rbenv-gem-rehash" ]]; then
  color_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..." cyan
    git clone https://github.com/sstephenson/rbenv-gem-rehash.git \
      ~/.rbenv/plugins/rbenv-gem-rehash
fi

if [[ ! -d "$HOME/.rbenv/plugins/ruby-build" ]]; then
  color_echo "Installing ruby-build, to install Rubies ..." cyan
    git clone https://github.com/sstephenson/ruby-build.git \
      ~/.rbenv/plugins/ruby-build
fi


#----------------------------------------------------------------------------//
# => SETUP RUBY ENVIRONMENT
#----------------------------------------------------------------------------//
ruby_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"

color_echo "Installing Ruby $ruby_version ..." cyan
  rbenv install -s "$ruby_version"

color_echo "Setting $ruby_version as global default Ruby ..." cyan
  rbenv global "$ruby_version"
  rbenv rehash

color_echo "Updating to latest Rubygems version ..." cyan
  gem update --system


#----------------------------------------------------------------------------//
# => BUNDLER FOR RUBY GEM INSTALLATION
#----------------------------------------------------------------------------//
color_echo "Installing Bundler to install project-specific Ruby gems ..." cyan
  gem install bundler --no-document --pre

color_echo "Configuring Bundler for faster, parallel gem installation ..." cyan
  number_of_cores=$(nproc)
  bundle config --global jobs $((number_of_cores - 1))


#----------------------------------------------------------------------------//
# => INSTALL IPYTHON NOTEBOOK (SYSTEM-WIDE)
#----------------------------------------------------------------------------//
color_echo "Installing IPython 2/3 notebook" cyan
  sudo apt-get install -y ipython ipython3 ipython-notebook ipython3-notebook

color_echo "Installing IPython 2/3 Qt console" cyan
  sudo apt-get install -y ipython-qt ipython3-qt


#----------------------------------------------------------------------------//
# => INSTALL SCIPY STACK
#----------------------------------------------------------------------------//
color_echo "Installing SciPy Stack ..." cyan
  sudo apt-get install python-numpy python-scipy python-matplotlib python-pandas python-sympy python-nose


#----------------------------------------------------------------------------//
# => INSTALL PYENV, PYTHON 2 AND 3 VERSION AND MODULE MANAGEMENT
#----------------------------------------------------------------------------//
if [[ ! -d "$HOME/.pyenv" ]]; then
  color_echo "Installing pyenv, to change Python versions ..." cyan
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
fi
