# Git aliases
alias g='git'
alias gst='git status'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias ga='git add'
alias gaa='git add .'
alias gap='git add --patch'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias glog='git log --oneline --graph --decorate'
alias gloga='git log --oneline --graph --decorate --all'
alias gundo='git reset HEAD~1'
alias gclean='git clean -fd'
