###############################################################################
#             /\/|  __
#            |/\/  / /      _______| |__  _ __ ___
#                 / /      |_  / __| '_ \| '__/ __|
#                / /    _   / /\__ \ | | | | | (__
#               /_/    (_) /___|___/_| |_|_|  \___|
#
# Last Updated: Fri 13 Mar 2020 10:15:29 AM CDT
#
#   Maintainer: Jose Elera (https://github.com/jelera)
#
#      License: MIT
#               Copyright (c) 2020 Jose Elera
#               Permission is hereby granted, free of charge, to any person
#               obtaining a copy of this software and associated documentation
#               files (the "Software"), to deal in the Software without
#               restriction, including without limitation the rights to use,
#               copy, modify, merge, publish, distribute, sublicense, and/or
#               sell copies of the Software, and to permit persons to whom the
#               Software is furnished to do so, subject to the following
#               conditions:
#
#               The above copyright notice and this permission notice shall be
#               included in all copies or substantial portions of the Software.
#
#               THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#               EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#               OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#               NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#               HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#               WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#               FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#               OTHER DEALINGS IN THE SOFTWARE.
###############################################################################


##---------------------------------------------------------------------------//
## => SOURCES
##---------------------------------------------------------------------------//
source ~/.config/dotfiles/shell/alias
source ~/.config/dotfiles/shell/shellscripts
source ~/.config/dotfiles/shell/env


##---------------------------------------------------------------------------//
## => OH-MY-ZSH CONFIG
##---------------------------------------------------------------------------//
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="candy"
ZSH_THEME="bira"
# ZSH_THEME="spaceship"

# SPACESHIP_TIME_SHOW="default"
# SPACESHIP_DIR_TRUNC=0

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDSHATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

#==============================================================================#
# => OH MY ZSH PLUGINS
#==============================================================================#
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
	vi-mode
	tmux
	tmuxinator
	git
	git-flow-avh
	git-extras
	git-prompt
	osx
	brew
	command-not-found
	rsync
	asdf
	ruby
	bundler
	# rails
	yarn
	npm
)

#==============================================================================#
# => ASDF
#==============================================================================#
# source /home/jelera/.asdf/asdf.sh
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash

#==============================================================================#
# => RVM
#==============================================================================#
eval "$(rbenv init -)"

#==============================================================================#
# => FZF
#==============================================================================#
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey -r "^E"
bindkey -r "^P"

#==============================================================================#
# => Support for Italics
#==============================================================================#
export TERM=xterm-256color-italic

source $ZSH/oh-my-zsh.sh

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
